apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  namespace: static
  labels:
    name: myingress
spec:
  rules:
  - host: static.sudha53.xyz
    http:
      paths:
        path: 
        backend:
          service:
            name: static
            port: 
              number: 80

